get firmware_url

diff --git a/.github/actions/init-environment/action.yml b/.github/actions/init-environment/action.yml
--- a/.github/actions/init-environment/action.yml
+++ b/.github/actions/init-environment/action.yml
@@ -25,6 +25,25 @@ runs:
         echo "manifest=$(cat src/main/resources/base/ayab/firmware/manifest.txt)" >> $GITHUB_OUTPUT
         echo "python=python${{matrix.python-version}}" >> $GITHUB_OUTPUT
         echo "python-appimage=python${{matrix.python-version}}.9-cp311-cp311-manylinux_2_28_x86_64.AppImage" >> $GITHUB_OUTPUT
+
+    - name: Get firmware version matching manifest
+      shell: bash
+      run: |
+        echo ${{ steps.vars.outputs.manifest }}
+        available=$(curl -s https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases | grep -oE '/tag/[^\"]+' | sed -E 's/\/tag\///')
+        echo $available
+        match=$(for x in $available; do echo $x; done | grep ^${{ steps.vars.outputs.manifest }} | sort -r | head -1)
+        echo $match
+        if [[ $match ]]
+        then
+          cd src/main/resources/base/ayab/firmware/
+          url=https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases/download/$match/ayab_monolithic_uno.hex
+          echo "firmware_url=${url}" >> $GITHUB_OUTPUT
+        else
+          echo "Error: could not find firmware release matching manifest"
+          exit 1
+        fi
+
     - name: Set PACKAGE_VERSION
       shell: bash
       run: |
