uncache other platforms

diff --git a/.github/workflows/build-multi-os.yml b/.github/workflows/build-multi-os.yml
--- a/.github/workflows/build-multi-os.yml
+++ b/.github/workflows/build-multi-os.yml
@@ -19,130 +19,6 @@ on:
       - "v?[0-9]+.[0-9]+.[0-9]+-?[a-zA-Z0-9]*"
 
 jobs:
-  setup:
-    name: Create cache
-    runs-on: ubuntu-22.04
-    strategy:
-      matrix:
-        python-version: [3.11]
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-        with:
-          submodules: recursive
-      - uses: ./.github/actions/init-environment
-        id: vars
-      - name: Get firmware version matching manifest
-        run: |
-          echo ${{ steps.vars.outputs.manifest }}
-          available=$(curl -s https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases | grep -oE '/tag/[^\"]+' | sed -E 's/\/tag\///')
-          echo $available
-          match=$(for x in $available; do echo $x; done | grep ^${{ steps.vars.outputs.manifest }} | sort -r | head -1)
-          echo $match
-          if [[ $match ]]
-          then
-            cd src/main/resources/base/ayab/firmware/
-            wget https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases/download/$match/ayab_monolithic_uno.hex
-          else
-            echo "Error: could not find firmware release matching manifest"
-            exit 1
-          fi
-      - name: Cache firmware
-        uses: actions/cache/save@v3
-        with:
-          path: src/main/resources/base/ayab/firmware/*.hex
-          key: firmware-${{ steps.vars.outputs.manifest }}
-      - name: Install dependencies
-        run: |
-          sudo apt update
-          sudo apt-get install -y avrdude libasound2-dev
-      - name: Install Python modules
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install --upgrade setuptools
-          python -m pip install -r requirements.build.txt
-      - name: Use cached gui files (1)
-        id: gui1-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/python/main/ayab/*_gui.py
-          key: gui1-${{ hashFiles('src/main/python/main/ayab/*_gui.ui') }}
-      - name: Use cached gui files (2)
-        id: gui2-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/python/main/ayab/engine/*_gui.py
-          key: gui2-${{ hashFiles('src/main/python/main/ayab/engine/*_gui.ui') }}
-      - name: Use cached logo
-        id: logo-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/python/main/ayab/ayab_logo_rc.py
-          key: logo-${{ hashFiles('src/main/python/main/ayab/ayab_logo_rc.qrc') }}
-      - name: Use cached graphics
-        id: e-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/python/main/ayab/engine/*_rc.py
-          key: e-${{ hashFiles('src/main/python/main/ayab/engine/*_rc.qrc') }}
-      - name: Use cached translation files
-        id: qm-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/resources/base/ayab/translations/*.qm
-          key: qm-${{ hashFiles('src/main/resources/base/ayab/translations/ayab-translation-master.tsv') }}
-      - name: Use cached `base.json` file
-        id: base-cache
-        uses: actions/cache@v3
-        with:
-          path: src/build/settings/base.json
-          key: base-${{ steps.vars.outputs.tag }}
-      - name: Convert UI and translation files
-        if: ${{ (steps.gui1-cache.outputs.cache-hit != 'true') ||
-          (steps.gui2-cache.outputs.cache-hit != 'true') ||
-          (steps.logo-cache.outputs.cache-hit != 'true') ||
-          (steps.e-cache.outputs.cache-hit    != 'true') ||
-          (steps.qm-cache.outputs.cache-hit   != 'true') }}
-        run: |
-          sudo apt install -y qt6-base-dev qt6-tools-dev-tools qt6-l10n-tools
-          PATH=/usr/lib/qt6/bin:$PATH bash setup-environment.ps1
-      - name: Cache gui files (1)
-        if: ${{ (steps.gui1-cache.outputs.cache-hit != 'true') }}
-        uses: actions/cache/save@v3
-        with:
-          path: src/main/python/main/ayab/*_gui.py
-          key: gui1-${{ hashFiles('src/main/python/main/ayab/*_gui.ui') }}
-      - name: Cache gui files (2)
-        if: ${{ (steps.gui2-cache.outputs.cache-hit != 'true') }}
-        uses: actions/cache/save@v3
-        with:
-          path: src/main/python/main/ayab/*_gui.py
-          key: gui2-${{ hashFiles('src/main/python/main/ayab/engine/*_gui.ui') }}
-      - name: Cache logo
-        if: ${{ (steps.logo-cache.outputs.cache-hit != 'true') }}
-        uses: actions/cache/save@v3
-        with:
-          path: src/main/python/main/ayab/ayab_logo_rc.py
-          key: logo-${{ hashFiles('src/main/python/main/ayab/ayab_logo_rc.qrc') }}
-      - name: Cache graphics
-        if: ${{ (steps.e-cache.outputs.cache-hit != 'true') }}
-        uses: actions/cache/save@v3
-        with:
-          path: src/main/python/main/ayab/engine/*_rc.py
-          key: e-${{ hashFiles('src/main/python/main/ayab/engine/*_rc.qrc') }}
-      - name: Cache translation files
-        if: ${{ (steps.qm-cache.outputs.cache-hit != 'true') }}
-        uses: actions/cache/save@v3
-        with:
-          path: src/main/resources/base/ayab/translations/*.qm
-          key: qm-${{ hashFiles('src/main/resources/base/ayab/translations/ayab-translation-master.tsv') }}
-      - name: Cache `base.json` file
-        if: ${{ (steps.base-cache.outputs.cache-hit != 'true') }}
-        uses: actions/cache/save@v3
-        with:
-          path: src/build/settings/base.json
-          key: base-${{ steps.vars.outputs.tag }}
-
   deploy:
     name: Create and deploy source code documentation
     runs-on: ubuntu-22.04
@@ -168,7 +44,6 @@ jobs:
 
   build-windows:
     name: Create and upload Windows release
-    needs: setup
     runs-on: windows-latest
     strategy:
       matrix:
@@ -189,62 +64,24 @@ jobs:
           python -m pip install --upgrade setuptools
           python -m pip install -r requirements.build.txt
           python -m pip install -r windows-build\windows_build_requirements.txt
-      - name: Restore cached firmware
-        id: firmware-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/resources/base/ayab/firmware/*.hex
-          key: firmware-${{ steps.vars.outputs.manifest }}
-          enableCrossOsArchive: true
-          fail-on-cache-miss: true
-      - name: Restore cached gui files (1)
-        id: gui1-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/python/main/ayab/*_gui.py
-          key: gui1-${{ hashFiles('src/main/python/main/ayab/*_gui.ui') }}
-          enableCrossOsArchive: true
-          fail-on-cache-miss: true
-      - name: Restore cached gui files (2)
-        id: gui2-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/python/main/ayab/engine/*_gui.py
-          key: gui2-${{ hashFiles('src/main/python/main/ayab/engine/*_gui.ui') }}
-          enableCrossOsArchive: true
-          fail-on-cache-miss: true
-      - name: Restore cached logo
-        id: logo-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/python/main/ayab/ayab_logo_rc.py
-          key: logo-${{ hashFiles('src/main/python/main/ayab/ayab_logo_rc.qrc') }}
-          enableCrossOsArchive: true
-          fail-on-cache-miss: true
-      - name: Restore cached graphics
-        id: e-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/python/main/ayab/engine/*_rc.py
-          key: e-${{ hashFiles('src/main/python/main/ayab/engine/*_rc.qrc') }}
-          enableCrossOsArchive: true
-          fail-on-cache-miss: true
-      - name: Restore cached translation files
-        id: qm-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/resources/base/ayab/translations/*.qm
-          key: qm-${{ hashFiles('src/main/resources/base/ayab/translations/ayab-translation-master.tsv') }}
-          enableCrossOsArchive: true
-          fail-on-cache-miss: true
-      - name: Restore cached `base.json` file
-        id: base-cache
-        uses: actions/cache@v3
-        with:
-          path: src/build/settings/base.json
-          key: base-${{ steps.vars.outputs.tag }}
-          enableCrossOsArchive: true
-          fail-on-cache-miss: true
+      - name: Get firmware version matching manifest
+        run: |
+          echo ${{ steps.vars.outputs.manifest }}
+          available=$(curl -s https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases | grep -oE '/tag/[^\"]+' | sed -E 's/\/tag\///')
+          echo $available
+          match=$(for x in $available; do echo $x; done | grep ^${{ steps.vars.outputs.manifest }} | sort -r | head -1)
+          echo $match
+          if [[ $match ]]
+          then
+            cd src/main/resources/base/ayab/firmware/
+            wget https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases/download/$match/ayab_monolithic_uno.hex
+          else
+            echo "Error: could not find firmware release matching manifest"
+            exit 1
+          fi
+      - name: Convert UI and translation files
+        run: |
+          bash setup-environment.ps1
       - name: Remove unneeded files
         shell: bash
         run: |
@@ -347,8 +184,6 @@ jobs:
           fi
       - name: Convert UI and translation files
         run: |
-          # sudo apt install -y qt6-base-dev qt6-tools-dev-tools qt6-l10n-tools
-          # PATH=/usr/lib/qt6/bin:$PATH 
           bash setup-environment.ps1
       - name: Remove unneeded files
         run: |
@@ -390,7 +225,6 @@ jobs:
   # see https://github.com/AppImage/AppImageKit/wiki/Bundling-Python-apps
   build-appimage:
     name: Create and upload Linux AppImage release
-    needs: setup
     runs-on: ubuntu-22.04
     strategy:
       matrix:
@@ -403,6 +237,34 @@ jobs:
           fetch-depth: 0
       - uses: ./.github/actions/init-environment
         id: vars
+
+      - name: Get firmware version matching manifest
+        run: |
+          echo ${{ steps.vars.outputs.manifest }}
+          available=$(curl -s https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases | grep -oE '/tag/[^\"]+' | sed -E 's/\/tag\///')
+          echo $available
+          match=$(for x in $available; do echo $x; done | grep ^${{ steps.vars.outputs.manifest }} | sort -r | head -1)
+          echo $match
+          if [[ $match ]]
+          then
+            cd src/main/resources/base/ayab/firmware/
+            wget https://github.com/AllYarnsAreBeautiful/ayab-firmware/releases/download/$match/ayab_monolithic_uno.hex
+          else
+            echo "Error: could not find firmware release matching manifest"
+            exit 1
+          fi
+
+      - name: Install Python modules
+        run: |
+          sudo apt-get install -y avrdude libasound2-dev
+          python -m pip install --upgrade pip
+          python -m pip install --upgrade setuptools
+          python -m pip install -r requirements.build.txt
+      - name: Convert UI and translation files
+        run: |
+          cd squashfs-root
+          bash setup-environment.ps1
+
       - name: Relocate
         run: |
           mkdir git
@@ -430,66 +292,6 @@ jobs:
         run: |
           echo "usr/bin" >> $GITHUB_PATH
           echo "opt/${{steps.vars.outputs.python}}/bin" >> $GITHUB_PATH
-      - name: Restore cached firmware
-        id: firmware-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/resources/base/ayab/firmware/*.hex
-          key: firmware-${{ steps.vars.outputs.manifest }}
-          fail-on-cache-miss: true
-      - name: Restore cached gui files (1)
-        id: gui1-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/python/main/ayab/*_gui.py
-          key: gui1-${{ hashFiles('src/main/python/main/ayab/*_gui.ui') }}
-          fail-on-cache-miss: true
-      - name: Restore cached gui files (2)
-        id: gui2-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/python/main/ayab/engine/*_gui.py
-          key: gui2-${{ hashFiles('src/main/python/main/ayab/engine/*_gui.ui') }}
-          fail-on-cache-miss: true
-      - name: Restore cached logo
-        id: logo-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/python/main/ayab/ayab_logo_rc.py
-          key: logo-${{ hashFiles('src/main/python/main/ayab/ayab_logo_rc.qrc') }}
-          fail-on-cache-miss: true
-      - name: Restore cached graphics
-        id: e-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/python/main/ayab/engine/*_rc.py
-          key: e-${{ hashFiles('src/main/python/main/ayab/engine/*_rc.qrc') }}
-          fail-on-cache-miss: true
-      - name: Restore cached translation files
-        id: qm-cache
-        uses: actions/cache@v3
-        with:
-          path: src/main/resources/base/ayab/translations/*.qm
-          key: qm-${{ hashFiles('src/main/resources/base/ayab/translations/ayab-translation-master.tsv') }}
-          fail-on-cache-miss: true
-      - name: Restore cached `base.json` file
-        id: base-cache
-        uses: actions/cache@v3
-        with:
-          path: src/build/settings/base.json
-          key: base-${{ steps.vars.outputs.tag }}
-          enableCrossOsArchive: true
-          fail-on-cache-miss: true
-      - name: Move cached files
-        run: |
-          mv src/main/resources/base/ayab/firmware/*.hex squashfs-root/src/main/resources/base/ayab/firmware/
-          mv src/main/python/main/ayab/*_gui.py squashfs-root/src/main/python/main/ayab/
-          mv src/main/python/main/ayab/engine/*_gui.py squashfs-root/src/main/python/main/ayab/engine/
-          mv src/main/python/main/ayab/ayab_logo_rc.py squashfs-root/src/main/python/main/ayab/
-          mv src/main/python/main/ayab/engine/lowercase_e_rc.py squashfs-root/src/main/python/main/ayab/engine
-          mv src/main/python/main/ayab/engine/lowercase_e_reversed_rc.py squashfs-root/src/main/python/main/ayab/engine
-          mv src/main/resources/base/ayab/translations/*.qm squashfs-root/src/main/resources/base/ayab/translations/
-          mv src/build/settings/base.json squashfs-root/src/build/settings/base.json
       - name: Remove unneeded files
         run: |
           rm squashfs-root/src/main/python/main/ayab/*_gui.ui
